# Generated by Django 6.0 on 2025-12-23 14:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mi_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
