# Generated by Django 6.0 on 2025-12-23 19:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mi_app", "0002_alter_cliente_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cliente",
            old_name="creado_en",
            new_name="created_at",
        ),
        migrations.AddField(
            model_name="cliente",
            name="activo",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="telefono",
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name="Direccion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("provincia", models.CharField(max_length=100)),
                ("municipio", models.CharField(max_length=100)),
                ("sector", models.CharField(max_length=100)),
                ("calle", models.CharField(blank=True, max_length=100, null=True)),
                ("numero_casa", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "nombre_residencial",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("manzana", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "nombre_edificio",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("piso", models.CharField(blank=True, max_length=10, null=True)),
                ("apartamento", models.CharField(blank=True, max_length=10, null=True)),
                ("referencia", models.TextField(blank=True, null=True)),
                ("notas", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="direcciones",
                        to="mi_app.cliente",
                    ),
                ),
            ],
        ),
    ]
