# Generated by Django 6.0 on 2025-12-29 12:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mi_app", "0004_producto"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="producto",
            name="stock",
        ),
        migrations.AddField(
            model_name="producto",
            name="tipo",
            field=models.CharField(
                choices=[("fisico", "Físico"), ("servicio", "Servicio")],
                default=django.utils.timezone.now,
                max_length=10,
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Inventario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.PositiveIntegerField()),
                ("actualizado", models.DateTimeField(auto_now=True)),
                (
                    "producto",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventario",
                        to="mi_app.producto",
                    ),
                ),
            ],
        ),
    ]
