# Generated by Django 6.0 on 2026-01-01 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mi_app", "0006_factura_facturadetalle"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inventario",
            name="cantidad",
        ),
        migrations.AddField(
            model_name="inventario",
            name="stock",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="factura",
            name="numero",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
