# Generated by Django 6.0 on 2026-01-01 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mi_app", "0007_remove_inventario_cantidad_inventario_stock_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="factura",
            name="numero",
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
